//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mar_sumaken_web.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagesResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mar_sumaken_web.Properties.ErrorMessagesResources", typeof(ErrorMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}は必須項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1001 {
            get {
                return ResourceManager.GetString("E1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{2}～{1}文字の間で正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1002 {
            get {
                return ResourceManager.GetString("E1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角英数字で正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1003 {
            get {
                return ResourceManager.GetString("E1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QRコードが正しくありません。正しいQRコードを読み取ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2001 {
            get {
                return ResourceManager.GetString("E2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリのバージョンが正しくありません。最新バージョンをダウンロードしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2002 {
            get {
                return ResourceManager.GetString("E2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}データがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2003 {
            get {
                return ResourceManager.GetString("E2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインIDが正しくありません。正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2004 {
            get {
                return ResourceManager.GetString("E2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベースに接続できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E3001 {
            get {
                return ResourceManager.GetString("E3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーに接続できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E3002 {
            get {
                return ResourceManager.GetString("E3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワークに接続できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E3003 {
            get {
                return ResourceManager.GetString("E3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQLServerでエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E4001 {
            get {
                return ResourceManager.GetString("E4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期せぬエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E9999 {
            get {
                return ResourceManager.GetString("E9999", resourceCulture);
            }
        }
    }
}
