//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mar_sumaken_web.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagesResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mar_sumaken_web.Properties.ErrorMessagesResources", typeof(ErrorMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}は必須項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1001 {
            get {
                return ResourceManager.GetString("E1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインIDまたはパスワードが正しくありません。正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1002 {
            get {
                return ResourceManager.GetString("E1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角英数字で正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1003 {
            get {
                return ResourceManager.GetString("E1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付指定に不正な値があります。半角YYYY/MM/DD形式で正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1004 {
            get {
                return ResourceManager.GetString("E1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付指定に不正な値があります。半角YYYYMMDD形式で正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1005 {
            get {
                return ResourceManager.GetString("E1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間指定に不正な値があります。半角HHMM形式で正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1006 {
            get {
                return ResourceManager.GetString("E1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値指定に不正な値があります。半角数字で正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1007 {
            get {
                return ResourceManager.GetString("E1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   規定の桁数に満たない、または超えている値があります。正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1008 {
            get {
                return ResourceManager.GetString("E1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この{0}は既に存在するため登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1009 {
            get {
                return ResourceManager.GetString("E1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が品番マスターに存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1010 {
            get {
                return ResourceManager.GetString("E1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が会社マスターに存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1011 {
            get {
                return ResourceManager.GetString("E1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルが選択されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1012 {
            get {
                return ResourceManager.GetString("E1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV形式でないファイルが含まれているため登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1013 {
            get {
                return ResourceManager.GetString("E1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル内にデータがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1014 {
            get {
                return ResourceManager.GetString("E1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクセス権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1015 {
            get {
                return ResourceManager.GetString("E1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   異なるログインを検出したため自動ログアウトされました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1016 {
            get {
                return ResourceManager.GetString("E1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力値に不正な値があります。正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1017 {
            get {
                return ResourceManager.GetString("E1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が仕入先かんばんマスターに存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1018 {
            get {
                return ResourceManager.GetString("E1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルが選択されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1019 {
            get {
                return ResourceManager.GetString("E1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に実績データがあるため、上書きできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1020 {
            get {
                return ResourceManager.GetString("E1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1}以上で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1021 {
            get {
                return ResourceManager.GetString("E1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入先かんばんマスターに一致するデータがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1022 {
            get {
                return ResourceManager.GetString("E1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{2}～{1}文字の間で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1023 {
            get {
                return ResourceManager.GetString("E1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重複許容フラグが0の場合、メインキーは必須項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1024 {
            get {
                return ResourceManager.GetString("E1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重複許容フラグが0の場合、「まとめ入庫」は選択できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1025 {
            get {
                return ResourceManager.GetString("E1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重複許容フラグが1の場合、「入庫」は選択できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1026 {
            get {
                return ResourceManager.GetString("E1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に実績データがあるため、削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1027 {
            get {
                return ResourceManager.GetString("E1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QRコードが正しくありません。正しいQRコードを読み取ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2001 {
            get {
                return ResourceManager.GetString("E2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}にデータがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2002 {
            get {
                return ResourceManager.GetString("E2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインIDが正しくありません。正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2003 {
            get {
                return ResourceManager.GetString("E2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続先を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2004 {
            get {
                return ResourceManager.GetString("E2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続先URLにアクセスできません。正しいURLを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2005 {
            get {
                return ResourceManager.GetString("E2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社コード・会社パスワードはセットで入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2006 {
            get {
                return ResourceManager.GetString("E2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用ハンディメニューが登録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2007 {
            get {
                return ResourceManager.GetString("E2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「設定」から会社コードを登録してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2008 {
            get {
                return ResourceManager.GetString("E2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリバージョンが取得できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2009 {
            get {
                return ResourceManager.GetString("E2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリのバージョンが正しくありません。最新バージョンをダウンロードしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2010 {
            get {
                return ResourceManager.GetString("E2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン情報が切断されました。再度ログインしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2011 {
            get {
                return ResourceManager.GetString("E2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続がタイムアウトしました。再度お試しください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2012 {
            get {
                return ResourceManager.GetString("E2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メニューが登録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2013 {
            get {
                return ResourceManager.GetString("E2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2014 {
            get {
                return ResourceManager.GetString("E2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QRコードの読取ができませんでした。再度スキャンしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2015 {
            get {
                return ResourceManager.GetString("E2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読取データがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2016 {
            get {
                return ResourceManager.GetString("E2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既にスキャン済みの仕入先かんばんです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2017 {
            get {
                return ResourceManager.GetString("E2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に実績データがあるため、登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2018 {
            get {
                return ResourceManager.GetString("E2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に実績データがあるため、一部データのみ登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2019 {
            get {
                return ResourceManager.GetString("E2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定の条件に合致する出荷指示がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2020 {
            get {
                return ResourceManager.GetString("E2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社コードまたは会社パスワードが正しくありません。正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2021 {
            get {
                return ResourceManager.GetString("E2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既にスキャン済みの納入先かんばんです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2022 {
            get {
                return ResourceManager.GetString("E2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納入先かんばんの品番・収容数と一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2023 {
            get {
                return ResourceManager.GetString("E2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷指示リストに一致するデータがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2024 {
            get {
                return ResourceManager.GetString("E2024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未検品の出荷指示がないためスキャンできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2025 {
            get {
                return ResourceManager.GetString("E2025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが正しくありません。正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2026 {
            get {
                return ResourceManager.GetString("E2026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫がマイナスになった品番があります。管理者に確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2027 {
            get {
                return ResourceManager.GetString("E2027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に実績データがあるため、一部データのみ登録しました。また、在庫がマイナスになった品番があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E2028 {
            get {
                return ResourceManager.GetString("E2028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベースに接続できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E3001 {
            get {
                return ResourceManager.GetString("E3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーに接続できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E3002 {
            get {
                return ResourceManager.GetString("E3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワークに接続できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E3003 {
            get {
                return ResourceManager.GetString("E3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベース処理実行中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E3004 {
            get {
                return ResourceManager.GetString("E3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期せぬエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E9999 {
            get {
                return ResourceManager.GetString("E9999", resourceCulture);
            }
        }
    }
}
