//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ai_truck_load_measurement.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagesResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ai_truck_load_measurement.Properties.ErrorMessagesResources", typeof(ErrorMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}は必須項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1001 {
            get {
                return ResourceManager.GetString("E1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインIDまたはパスワードが正しくありません。正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1002 {
            get {
                return ResourceManager.GetString("E1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は4桁の半角数字で正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1003 {
            get {
                return ResourceManager.GetString("E1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付指定に不正な値があります。半角YYYY/MM/DD形式で正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1004 {
            get {
                return ResourceManager.GetString("E1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間指定に不正な値があります。半角HHMM形式で正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1005 {
            get {
                return ResourceManager.GetString("E1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択した期間に実績が存在しない便が選択されています。期間を修正するか、便を削除してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1006 {
            get {
                return ResourceManager.GetString("E1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索できる期間は最長90日です。90日を超えないように選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1007 {
            get {
                return ResourceManager.GetString("E1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択できる便数は最大20件です。20件を超えないように選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1008 {
            get {
                return ResourceManager.GetString("E1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択できる稼働日は最大20日です。20日を超えないように選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1009 {
            get {
                return ResourceManager.GetString("E1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この{0}は既に存在するため登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1010 {
            get {
                return ResourceManager.GetString("E1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力値に不正な値があります。正しい値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1011 {
            get {
                return ResourceManager.GetString("E1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録済みの便の適用開始/終了日時がかぶるため登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1012 {
            get {
                return ResourceManager.GetString("E1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この{0}はAD内に存在しないため登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1013 {
            get {
                return ResourceManager.GetString("E1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メール受け取りが必要な場合、メールアドレスを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1014 {
            get {
                return ResourceManager.GetString("E1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1015 {
            get {
                return ResourceManager.GetString("E1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力されるデータがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1016 {
            get {
                return ResourceManager.GetString("E1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E1017 {
            get {
                return ResourceManager.GetString("E1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベースに接続できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E3001 {
            get {
                return ResourceManager.GetString("E3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーに接続できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E3002 {
            get {
                return ResourceManager.GetString("E3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワークに接続できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E3003 {
            get {
                return ResourceManager.GetString("E3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベース処理実行中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E3004 {
            get {
                return ResourceManager.GetString("E3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期せぬエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E9999 {
            get {
                return ResourceManager.GetString("E9999", resourceCulture);
            }
        }
    }
}
